name: Build Nginx (MSYS2)

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Введите git tag/branch nginx (например: release-1.28.0, main). Оставьте пустым или "latest" для последнего.'
        required: false
        default: ''
        type: string
  push:
    paths:
      - '.github/workflows/build-nginx.yml'
      - 'nginx-build-msys2-new.sh'
      - 'nginx-package-msys2.sh'
      - 'nginx-*.patch'

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            git
            wget
            curl
            tar
            xz
            bzip2
            patch
            perl
            p7zip
            pkgconf
            mingw-w64-x86_64-gd
            mingw-w64-x86_64-libheif
            mingw-w64-x86_64-libavif
            mingw-w64-x86_64-aom
            mingw-w64-x86_64-dav1d
            mingw-w64-x86_64-rav1e
            mingw-w64-x86_64-libyuv
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-brotli
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libtiff
            mingw-w64-x86_64-openjpeg2
            mingw-w64-x86_64-openh264
            mingw-w64-x86_64-x265
            mingw-w64-x86_64-kvazaar
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-libimagequant
            mingw-w64-x86_64-jbigkit
            mingw-w64-x86_64-libdeflate
            mingw-w64-x86_64-lerc
            mingw-w64-x86_64-xz
            mingw-w64-x86_64-zstd
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-pcre2
            mingw-w64-x86_64-geoip
            mingw-w64-x86_64-libmaxminddb

      - name: Prepare Git identity (anonymous)
        run: |
          NAME="${{ github.actor }}"
          EMAIL="${{ github.actor }}@users.noreply.github.com"
          echo "BUILD_USER_NAME=$NAME"  >> $GITHUB_ENV
          echo "BUILD_USER_EMAIL=$EMAIL" >> $GITHUB_ENV

      - name: Normalize TAG input
        run: |
          RAW="${{ github.event.inputs.TAG }}"
          if [ -z "$RAW" ] || [ "$RAW" = "latest" ]; then
            echo "TAG=" >> $GITHUB_ENV
          else
            echo "TAG=$RAW" >> $GITHUB_ENV
          fi

      - name: Show toolchain versions
        run: |
          gcc --version
          g++ --version
          make --version
          perl --version
          7z

      - name: Build nginx (Release + Debug)
        env:
          TAG: ${{ env.TAG }}
          BUILD_USER_NAME: ${{ env.BUILD_USER_NAME }}
          BUILD_USER_EMAIL: ${{ env.BUILD_USER_EMAIL }}
        run: |
          chmod +x ./nginx-build-msys2-new.sh
          ./nginx-build-msys2-new.sh

      - name: Package nginx
        run: |
          chmod +x ./nginx-package-msys2.sh
          ./nginx-package-msys2.sh

      - name: Upload artifacts (executables)
        uses: actions/upload-artifact@v4
        with:
          name: nginx-executables
          path: Release/*.exe

      - name: Upload artifacts (package)
        uses: actions/upload-artifact@v4
        with:
          name: nginx-package
          path: |
            Release/nginx-bin.7z
            Release/docs/**
            Release/conf/**
            Release/html/**
            Release/contrib/**